databases:
  - name: mysql
    databaseName: jobdata
    user: b_user
    ipAllowList: [ ]

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mysql
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: [ ]
    plan: free
    maxmemoryPolicy: noevicion